### ISSUE TITLE
rating_votes is empty

### ISSUE THREAD

**Issue by adminko-svk** [hmerritt/php-imdb-api#19]
Hi, 
rating_votes attribute is empty due to changed IMDb HTML structure for this value.
Please check and fix.
Thank you.

**Comment by adminko-svk** [comment]
I changed 
`imdb-api/src/HtmlPieces.php:121`
to
`$patterns = [".sc-bde20123-3"];` 
as a temporary solution.

**Comment by hmerritt** [comment]
> I changed `imdb-api/src/HtmlPieces.php:121` to `$patterns = [".sc-bde20123-3"];` as a temporary solution.

I have added this as a hotfix, since it does work.

---

It is somewhat hard to find a more stable pattern given the markup.

I tried to use the data in `__NEXT_DATA__` script, but this is not always present, so I abandoned it.

Will look into other options, for now though I've added the hotfix and will close this issue.

---

Thanks for making the issue and feel free to create more if any other issues crop up!
